name: "Commits Within Time" 
description: "A helper action that returns true if commits are detected on a repository within a supplied timeframe." 
branding:
  icon: git-commit
  color: blue
inputs:
  seconds:
    description: "How many seconds back you'd like to check from the workflow's current time." 
    required: false
    default: 0
  minutes: 
    description: "How many minutes back you'd like to check from the workflow's current time." 
    required: false
    default: 0
  hours: 
    description: "How many hours back you'd like to check from the workflow's current time." 
    required: true
    default: 24
  days: 
    description: "How many days back you'd like to check from the workflow's current time." 
    required: false
    default: 0
  months: 
    description: "How many months back you'd like to check from the workflow's current time." 
    required: false
    default: 0
  years: 
    description: "How many years back you'd like to check from the workflow's current time." 
    required: false
    default: 0
  usernamesToIgnore:
    description: "Commits authored or committed by usernames listed here will be ignored in the check."
    required: false
    default: '{"ignoredUsernamesList": ["ExampleBlockedUsername1","ExampleBlockedUsername2"]}'
  emailAddressesToIgnore:
    description: "Commits authored or committed by email addresses listed here will be ignored in the check."
    required: false
    default: '{"ignoredEmailAddressesList": ["exampleIgnoredEmail@test.com","exampleIgnoredEmail@email.com"]}'
  usernamesToFocus:
    description: "Commits authored or committed by usernames listed here will be the ONLY commits considered in the check."
    required: false
    default: '{"allowedUsernamesList": []}'
  emailAddressesToFocus:
    description: "Commits authored or committed by email addresses listed here will be the ONLY commits considered in the check."
    required: false
    default: '{"allowedEmailAddressesList": []}'
  includeGithubActor:
    description: "If set to true, commits by the user who triggered this workflow will be included in the check. Default is true."
    required: false
    default: true
  includeActionsUser:
    description: "If set to true, commits by the 'actions-user' Github Actions account will be included in the check. Default is false."
    required: false
    default: false
  exportToFile:
    description: "Set to true if you want the result of this Action to be stored as a JSON file in your repository's Artifact section."
    required: false
    default: false
outputs:
  has-new-commits-within-time:
    description: "True or false, depending on if commits have been detected with a timestamp within the specified timeframe." 
  number-of-commits-within-time:
    description: "Whole number of commits detected that are within the specified timeframe." 
  total-commits:
    description: "Whole number of commits detected on the repository/branch overall, even the ones not within the specified timeframe." 
runs:
  using: "node12" 
  main: "src/index.js" 